---
name: 🐛 Bug report
description: Track a verified issue or bug on on the Cloudflare developer platform.
type: Bug
---

# Important (Please Read)

This repo is NOT a generalized support forum or issue tracker. 
This repo is for tracking *verified* and *reproducible* issues only.
Issues that cannot be independently verified and reproduced will be automatically closed.

Please use the following alternatives for more developer/customer focused support:
  - [Cloudflare Support](https://dash.cloudflare.com/?to=/:account/support) 
  - [Cloudflare Discord](https://discord.cloudflare.com)
  - [Cloudflare community forum](https://community.cloudflare.com)
  - [Repo: Workers SDK Monorepo (wrangler, vite plugin, etc.)](https://github.com/cloudflare/workers-sdk)

If you understand the specialized purpose of this repo and wish to continue, delete this section of the template and then please fill out the rest.

### Describe the Bug

<!-- A clear and concise description of what the issue is. -->

### Expected Behavior

<!-- What did you expect to happen instead? -->

### Steps to Reproduce

<!-- Starting from one of the examples at https://developers.cloudflare.com/workers/examples/, or a basic hello world. -->

1.
2.
3.
