blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/cloudflare/cf-platform-issues/discussions/new
    about: Propose and discuss new features, improvements, and RFCs.
