blank_issues_enabled: false
contact_links:
  - name: Customer Support
    url: https://dash.cloudflare.com/?to=/:account/support
    about: Recommended. If you are having trouble with your account, start here.